service: firestore-chat-api
provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1
  profile: dev1
  environment:
    MESSAGE_COLLECTION_NAME: 'messages'
    IMAGE_COLLECTION_NAME: 'images'
functions:
  getMessages:
    handler: index.getMessages
    events:
      - http:
          method: get
          path: messages
          cors: true
          request:
            parameters:
              querystrings:
                limit: true
                startAfterId: true
  postMessages:
    handler: index.postMessages
    events:
      - http:
          method: post
          path: messages
          cors: true
  deleteMessages:
    handler: index.deleteMessages
    events:
      - http:
          method: delete
          path: messages/{id}
          cors: true
          request:
            parameters:
              paths:
                id: true
  getImages:
    handler: index.getImages
    events:
      - http:
          method: get
          path: images
          cors: true
          request:
            parameters:
              querystrings:
                limit: true
                startAfterId: true
  postImages:
    handler: index.postImages
    events:
      - http:
          method: post
          path: images
          cors: true
  deleteImages:
    handler: index.deleteImages
    events:
      - http:
          method: delete
          path: images/{id}
          cors: true
          request:
            parameters:
              paths:
                id: true
