service: firestore-chat-api
provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1
  profile: dev1
  environment:
    MESSAGE_COLLECTION_NAME: 'messages'
    IMAGE_COLLECTION_NAME: 'images'
functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
      - http:
        cors: true
